"""empty message

Revision ID: 0e8b355adb04
Revises: 
Create Date: 2025-02-23 10:58:22.727308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e8b355adb04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parent_id', mysql.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('status', postgresql.ENUM('0', '1', '2', '3', '4', '5', '6', '7', '8', name='crawling_status'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_status'), 'url', ['status'], unique=False)
    op.create_table('author',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('web_site', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index',
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('author_id', mysql.BIGINT(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    op.drop_table('index')
    op.drop_table('content')
    op.drop_table('author')
    op.drop_index(op.f('ix_url_status'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
