"""empty message

Revision ID: 6b1d2bc0d2ad
Revises:
Create Date: 2025-03-23 13:06:31.586293

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision: str = "6b1d2bc0d2ad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predefined_url",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("exception_info", sa.String(), nullable=True),
        sa.Column("task_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("status", postgresql.ENUM("1", "2", "3", "4", name="predefined_url_status"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_predefined_url_status"), "predefined_url", ["status"], unique=False)
    op.create_table(
        "scheduled_url",
        sa.Column("task_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scheduled_time", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("exception_info", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("status", postgresql.ENUM("1", "2", "3", "4", name="scheduled_url_status"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduled_url_status"), "scheduled_url", ["status"], unique=False)
    op.create_table(
        "url",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("crawled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "status", postgresql.ENUM("0", "1", "2", "3", "4", "5", "6", "7", "8", name="crawling_status"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_url_status"), "url", ["status"], unique=False)
    op.create_table(
        "author",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("web_site", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["url.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["url.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "index",
        sa.Column("keyword", sa.String(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["url.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meta",
        sa.Column("author_id", mysql.BIGINT(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["url.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meta")
    op.drop_table("index")
    op.drop_table("content")
    op.drop_table("author")
    op.drop_index(op.f("ix_url_status"), table_name="url")
    op.drop_table("url")
    op.drop_index(op.f("ix_scheduled_url_status"), table_name="scheduled_url")
    op.drop_table("scheduled_url")
    op.drop_index(op.f("ix_predefined_url_status"), table_name="predefined_url")
    op.drop_table("predefined_url")
    # ### end Alembic commands ###
